Gif.py update
PizzaDAO/pizza-discord-bots pull request #28
Opened 2021-05-09 22:07 UTC by Jkratz01

Added changes requested earlier

2021-05-11 16:54 UTC, ocanash1 requested changes

2021-05-11 16:54 UTC, ocanash1 commented on cogs/gif.py
> +
still need to remove some of these empty lines

2021-05-11 16:54 UTC, ocanash1 commented on cogs/gif.py
> +
remove 1 line here

2021-05-27 15:43 UTC, keithrfung approved these changes

2022-03-25 03:42 UTC, merged